# 服务器配置
server:
  port: "8091"

# Emby 配置
emby:
  host: "http://192.168.0.109:8096" # 您的 Emby 服务器地址
  api_key: ""                      # 可选。如果留空，程序会自动从客户端请求中获取

  strm:
    path-map:
      # 将 Emby 返回的媒体路径中的片段替换为新内容
      # 格式: "旧地址片段 => 新地址片段"
      - "http://127.0.0.1:12395 => https://your.public.domain.com"

  # 下载接口处理策略 (目前只支持 403)
  download-strategy: 403

# 客户端防火墙 (全局访问控制)
ClientFilter:
  Enable: false                             # 是否启用 (true/false)
  Mode: BlackList                           # 模式: BlackList (黑名单) 或 WhiteList (白名单)
  ClientList:                               # 客户端名称列表 (User-Agent 部分匹配)
    - Infuse
    - Fileball